# Site settings
title: 艾伦.M
email: wuwei.allenming@gmail.com
description: Game Develpoer的人生感悟
baseurl: "" # the subpath of your site, e.g. /blog/
url: "awAlive.top" # the base hostname & protocol for your site
twitter_username: AlifeAw
github_username:  AllenSky

# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
